//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StephenCoreMed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Customer()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Notes = new HashSet<Note>();
            this.Documents = new HashSet<Document>();
        }
    
        public int CE_Id { get; set; }
        public string CE_Name { get; set; }
        public string CE_Title { get; set; }
        public string CE_Email { get; set; }
        public string CE_PhoneNumber { get; set; }
        public string CE_CellNumber { get; set; }
        public string CE_Address { get; set; }
        public Nullable<int> C_ID_Fk { get; set; }
        public string CE_Description { get; set; }
        public string CE_City { get; set; }
        public string CE_State { get; set; }
        public string CE_Country { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EC_Type { get; set; }
        public string DepartmentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
