//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StephenCoreMed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int N_Id { get; set; }
        public string N_Topic { get; set; }
        public string N_Discussion { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> C_Id_FK { get; set; }
        public Nullable<int> Customer_Id_FK { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee_Customer Employee_Customer { get; set; }
    }
}
